CREATE TABLE "Tabian" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" text NOT NULL,
	"info" boolean,
	"score1_user1" integer,
	"score1_user2" integer,
	"score2_user1" integer,
	"score2_user2" integer,
	"score3_user1" integer,
	"score3_user2" integer,
	"score4_user1" integer,
	"score4_user2" integer,
	"score5_user1" integer,
	"score5_user2" integer,
	"score6_1_user1" integer,
	"score6_1_user2" integer,
	"score6_2_user1" integer,
	"score6_2_user2" integer,
	"score1_user1_staffUsername" text NOT NULL,
	"score1_user2_staffUsername" text NOT NULL,
	"score2_user1_staffUsername" text NOT NULL,
	"score2_user2_staffUsername" text NOT NULL,
	"score3_user1_staffUsername" text NOT NULL,
	"score3_user2_staffUsername" text NOT NULL,
	"score4_user1_staffUsername" text NOT NULL,
	"score4_user2_staffUsername" text NOT NULL,
	"score5_user1_staffUsername" text NOT NULL,
	"score5_user2_staffUsername" text NOT NULL,
	"score6_1_user1_staffUsername" text NOT NULL,
	"score6_1_user2_staffUsername" text NOT NULL,
	"score6_2_user1_staffUsername" text NOT NULL,
	"score6_2_user2_staffUsername" text NOT NULL,
	"updatedAt_score1_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score1_user2" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score2_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score2_user2" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score3_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score3_user2" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score4_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score4_user2" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score5_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score5_user2" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score6_1_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score6_1_user2" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score6_2_user1" timestamp DEFAULT NOW() NOT NULL,
	"updatedAt_score6_2_user2" timestamp DEFAULT NOW() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Wichakarn" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" text NOT NULL,
	"scoreAcademic" integer,
	"scoreChess" integer,
	"status" text DEFAULT 'unlock' NOT NULL,
	"staffUsername" text NOT NULL,
	"updated_at" timestamp DEFAULT NOW() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "Tabian_userId_idx" ON "Tabian" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "Wichakarn_userId_idx" ON "Wichakarn" USING btree ("userId" text_ops);